### ISSUE TITLE
[Bug]: CTD in pandora without animations being loaded & critical failure

### ISSUE THREAD

**Issue by imanoobyasu0** [Monitor144hz/Pandora-Behaviour-Engine-Plus#195] opened 2024-04-21 02:12 UTC
### Check for duplicate issues

- [X] I have verified that there are no duplicate [issues](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues).

### Version

v1.4.0-alpha

### Provide Instructions on Reproducing the Problem

With book of shadows patch, pandora crashes without any animations loaded. Also got a critical failure error for other patches without book of shadows patch

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/15050429/Engine.log)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by oren19737373** [comment] 2024-04-21 03:00
CRITICAL FAILURE TO ACTIVATE  Book Of Shadows  Flinching Animations

**Comment by Monitor144hz** [comment] 2024-04-21 10:58
Check v1.4.1-alpha

**Comment by oren19737373** [comment] 2024-04-21 14:55
CRITICAL FAILURE 

If the cause is unknown: submit a report to the author of the engine and attach Engine.log
Launch aborted. Existing output was not cleared, and current patch list will not be saved.
Book Of Shadows
[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/15052378/Engine.log)

**Comment by Monitor144hz** [comment] 2024-05-03 12:35
Should be fixed in latest version.

**Closed by Monitor144hz** 2024-05-03 12:35 UTC
Labels: bug
