### ISSUE TITLE
Varous mods not fully working i found so far

### ISSUE THREAD

**Issue by sidfu** [Monitor144hz/Pandora-Behaviour-Engine-Plus#71] opened 2024-01-07 23:26 UTC
1. [this](https://www.nexusmods.com/skyrimspecialedition/mods/28451)  doesn't work at all. adding thru OAR/DAR doesn't work either.
2. zaz animations parts not working. not checked everything but zaz milk pumps wont work at all.
3. torch idles do not work. both normal  and adding thru OAR/DAR  the wont work.
4. SGO4 aka soul gem oven 4 animations dont play

**Comment by Rolothe5th** [comment] 2024-01-08 20:02
along with this some mods from immersive interactions and immersive equipments is partially working

**Comment by imanoobyasu0** [comment] 2024-01-10 04:45
Dk is it related but with pandora i also have issues with TK dodge RE - Script free.

**Comment by Rolothe5th** [comment] 2024-01-10 04:46
> Dk is it related but with pandora i also have issues with TK dodge RE - Script free.

ight so issue with tke dodge re is that its not using AMR so that pandora can register it so will probably need to use something like tudm or dmco

**Comment by MaskPlague** [comment] 2024-01-12 09:20
> > Dk is it related but with pandora i also have issues with TK dodge RE - Script free.
> 
> ight so issue with tke dodge re is that its not using AMR so that pandora can register it so will probably need to use something like tudm or dmco

TK dodge RE - Script free works almost 100% fine. I'm using the standalone version and it only has a super small delay in-between dodges. Just make sure it is near the top of the list. 
My priority order is:
SBE - True Prone System
Attack - Modern Combat Overhaul
Payload Interpreter
TK Dodge Standalone
Etc.

**Comment by Monitor144hz** [comment] 2024-01-15 18:19
Investigating

**Comment by IngridRe** [comment] 2024-01-16 18:11
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Replace > Element > #0168/generator > FAILED
WARN : Dispatcher > "True Directional Movement - 360 Horse Archery" > defaultfemale~horsebehavior > Replace > Text > #0742/errorOutTranslation > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/eventNames > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/eventNames > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/eventNames > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/eventNames > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/variableNames > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/variableNames > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/variableNames > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/variableNames > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0079/wordVariableValues > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0079/wordVariableValues > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0079/wordVariableValues > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0079/wordVariableValues > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/variableInfos > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/variableInfos > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/variableInfos > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/variableInfos > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/eventInfos > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/eventInfos > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/eventInfos > FAILED
WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/eventInfos > FAILED
WARN : Dispatcher > "Elden Counter - Stun&Poise Damage" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Dispatcher > "Elden Counter - NPC Counter Behavior" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Dispatcher > "HotKeySkill" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Dispatcher > "SCAR" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Dispatcher > "TK Dodge RE / Ultimate Combat" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Dispatcher > "Distar Unblockable" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > Collision_Start > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > PIE > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Variable > tdmHeadtrackingBehavior > REMOVED
WARN : Validator > defaultfemale~1hm_behavior > Duplicate Variable > bAnimationDriven > REMOVED
WARN : Dispatcher > "Elden Counter - Stun&Poise Damage" > defaultmale~0_master > Replace > Element > #0260/event/Element0/id > FAILED
WARN : Dispatcher > "Vitrium" > defaultmale~0_master > Replace > Text > #0107/quadVariableValues > FAILED
WARN : Dispatcher > "Vitrium" > defaultmale~0_master > Replace > Text > #0107/quadVariableValues > FAILED

I assume all these mods are incompatible?

**Comment by Monitor144hz** [comment] 2024-01-16 22:49
> WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Replace > Element > #0168/generator > FAILED WARN : Dispatcher > "True Directional Movement - 360 Horse Archery" > defaultfemale~horsebehavior > Replace > Text > #0742/errorOutTranslation > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/eventNames > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/eventNames > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/eventNames > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/eventNames > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/variableNames > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/variableNames > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/variableNames > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0078/variableNames > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0079/wordVariableValues > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0079/wordVariableValues > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0079/wordVariableValues > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0079/wordVariableValues > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/variableInfos > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/variableInfos > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/variableInfos > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/variableInfos > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/eventInfos > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/eventInfos > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/eventInfos > FAILED WARN : Dispatcher > "Flinching Animations" > dogproject~wolfbehavior > Append > Element > #0080/eventInfos > FAILED WARN : Dispatcher > "Elden Counter - Stun&Poise Damage" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED WARN : Dispatcher > "Elden Counter - NPC Counter Behavior" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED WARN : Dispatcher > "HotKeySkill" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED WARN : Dispatcher > "SCAR" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED WARN : Dispatcher > "TK Dodge RE / Ultimate Combat" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED WARN : Dispatcher > "Distar Unblockable" > defaultfemale~1hm_behavior > Replace > Element > #2521/event/Element0/id > FAILED WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > Collision_Start > REMOVED WARN : Validator > defaultfemale~1hm_behavior > Duplicate Event > PIE > REMOVED WARN : Validator > defaultfemale~1hm_behavior > Duplicate Variable > tdmHeadtrackingBehavior > REMOVED WARN : Validator > defaultfemale~1hm_behavior > Duplicate Variable > bAnimationDriven > REMOVED WARN : Dispatcher > "Elden Counter - Stun&Poise Damage" > defaultmale~0_master > Replace > Element > #0260/event/Element0/id > FAILED WARN : Dispatcher > "Vitrium" > defaultmale~0_master > Replace > Text > #0107/quadVariableValues > FAILED WARN : Dispatcher > "Vitrium" > defaultmale~0_master > Replace > Text > #0107/quadVariableValues > FAILED
> 
> I assume all these mods are incompatible?

Elden Counter, Distar Unblockable, HotkeySkill, SCAR, Vitrium all have dirty edits that failed (rightfully so). Nothing wrong there. 

Flinching animations on the other hand, I think is targeting the wrong file (if it doesn't work in game). I'll add it to the to do list.

**Comment by Monitor144hz** [comment] 2024-02-01 22:55
Duplicate of #76

**Closed by Monitor144hz** 2024-02-01 22:55 UTC
Labels: duplicate
