### ISSUE TITLE
[Bug]: "Milk Mod Economy" has bug in machine animaiton

### ISSUE THREAD

**Issue by GaryjackYzee** [Monitor144hz/Pandora-Behaviour-Engine-Plus#167] opened 2024-04-02 10:45 UTC
### Version

1.2.2 alpha

### Provide Instructions on Reproducing the Problem

Milk pump machine animations from "[Milk Mod Economy SE 22-05-2022](https://www.loverslab.com/files/file/6103-milk-mod-economy-se/)" were not playing. I only tested it while standing. However , it works successfully in FNIS.

This mod has some animations like "Milk pump manual" works  successfully.

### Provide Relevant Files

[Engine.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14835364/Engine.log)
[FNIS animationdatasinglefile.txt](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14835380/FNIS.animationdatasinglefile.txt)
[Pandora animationdatasinglefile.txt](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14835382/Pandora.animationdatasinglefile.txt)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment] 2024-05-03 12:42
duplicate of #76

**Closed by Monitor144hz** 2024-05-03 12:42 UTC
Labels: bug
