### ISSUE TITLE
[Bug]: TK Dodge RE step dodge incompatibility

### ISSUE THREAD

**Issue by ElmoDFGD** [Monitor144hz/Pandora-Behaviour-Engine-Plus#137] opened 2024-03-08 21:07 UTC
### Version

1.1.8-alpha

### Provide Instructions on Reproducing the Problem

1.5.97
Step dodge doesn't work for TK Dodge RE.

P.s. no teleportation in video, just shitty editing skills. Sorry.

### Provide Relevant Files

[PandoraandNemesisOutput.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14543118/PandoraandNemesisOutput.zip)
[modlist.txt](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14543119/modlist.txt)

### Provide Visual Proof (optional)

https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/118224262/b0dca278-c29b-413b-8e3f-37b275e540ad

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by ElmoDFGD** [comment] 2024-03-08 21:12
[nemesisoutput.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14543199/nemesisoutput.zip)
Nemesis output was empty

**Comment by SteveTownsend** [comment] 2024-03-08 21:40
Have you tried this?
https://www.nexusmods.com/skyrimspecialedition/mods/111788

**Comment by ElmoDFGD** [comment] 2024-03-08 21:46
Yep, only works for dodge roll from what I understand. Thanks for the input though!

**Comment by ElmoDFGD** [comment] 2024-03-08 21:49
Actually, reading the mod page again it should work for step dodge. Didn't work for me in the testing though :O

**Comment by sensirou** [comment] 2024-03-11 11:53
TK Dodge RE work fine with me. I.m using SE 1.57, Nemesis and pandora.

**Comment by ElmoDFGD** [comment] 2024-03-11 12:08
Oh, didn't know it was possible to combine them. Might be useful as a work around, but I feel like using two behavior engines is a risky endeavor.

**Comment by elbadcode** [comment] 2024-03-19 01:04
there's no point in using nemesis by now but yes you can use any behavior engine together so long as the mods are working correctly. Prior to native fnis handling I used to combine them to get full functionality. Pandora patches will break nemesis but running pandora last is fine, its just not useful. You can use the patches from nemesis without running the behavior engine but I'm not sure if thats necessary for any mods anymore.


anyway it looks like the issue is you're using a rare variant of tk dodge. never heard of "tk dodge (shorter dodge)" but just stick to the latest tk dodge re with the pandora patch which I believe only needs the AMR annotations for the full length dodge anyway. I use DMCO for step dodges and recommend the same

**Comment by ElmoDFGD** [comment] 2024-03-19 12:49
Thanks for your reply! I have tried the original tk dodge animations, both patched and unpatched. Step dodging still doesn't work unfortunately. Which version of DMCO are you using?

**Comment by elbadcode** [comment] 2024-03-19 18:23
2.1.1.9 I believe. If using mco I recommend checking nexus for the recent MCO input buffer mod and dmco attack cancel generator tool to get the most out of the mod. I use dmco and tk dodge simultaneously on different keys just for some variety

**Comment by ElmoDFGD** [comment] 2024-03-20 09:12
So I got it all working by having Nemesis and the patch installed and then running Pandora. The Input buffer is amazing, thank you. Side note - had to switch from Dual Parry Reimplementation to Dual Wield Parry - SKSE for compatibility with Smooth Input.

@Monitor144hz Do you want me to close the issue?

**Comment by edjiang000** [comment] 2024-05-03 05:33
I got step-dodge to work without using nemesis. Here's my process:

1. Install TK Dodge SE, make sure to tick TK Dodge Standalone in the FOMOD: https://www.nexusmods.com/skyrimspecialedition/mods/15309
2. Install TK Dodge RE - Script Free: https://www.nexusmods.com/skyrimspecialedition/mods/56956?tab=files
3. Install TK Dodge NG: https://www.nexusmods.com/skyrimspecialedition/mods/115408
4. Install TK Dodge Animation Pandora Fix Patch: https://www.nexusmods.com/skyrimspecialedition/mods/111788
5. Arrange your load order like this: 
![image](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/116089553/2a7f67b4-96a7-493f-8230-11c34d95fec1)
6. Configure step dodge (StepDodge = true on line 12) and other settings in the TK Dodge NG ini file
7. Run Pandora and check the "TK Dodge Standalone" option. Do not check the "TK Dodge RE / Ultimate Combat" option

**Comment by Monitor144hz** [comment] 2024-05-03 07:49
> I got step-dodge to work without using nemesis on 1.6.640.0. Here's my process:
> 
>     1. Install TK Dodge SE, make sure to tick TK Dodge Standalone in the FOMOD: https://www.nexusmods.com/skyrimspecialedition/mods/15309
> 
>     2. Install TK Dodge RE - Script Free: https://www.nexusmods.com/skyrimspecialedition/mods/56956?tab=files
> 
>     3. Install TK Dodge NG: https://www.nexusmods.com/skyrimspecialedition/mods/115408
> 
>     4. Install TK Dodge Animation Pandora Fix Patch: https://www.nexusmods.com/skyrimspecialedition/mods/111788
> 
>     5. Arrange your load order like this:
>        ![image](https://private-user-images.githubusercontent.com/116089553/327653299-2a7f67b4-96a7-493f-8230-11c34d95fec1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjI2MjYsIm5iZiI6MTcxNDcyMjMyNiwicGF0aCI6Ii8xMTYwODk1NTMvMzI3NjUzMjk5LTJhN2Y2N2I0LTk2YTctNDkzZi04MjMwLTExYzM0ZDk1ZmVjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwNzQ1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzZkMGRlYWMwYTI4MmFhNzhhNTMxYTQ0YzJhZGYxZGIyNzhhYTQ0YmY5MWQxNDE0NTgyMDE1N2Y5ZGEzNWM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vrW4O7z6ZJPPmGmanf8-LeBMBlpGCwehkZQkHbzeEUw)
> 
>     6. Configure step dodge (StepDodge = true on line 12) and other settings in the TK Dodge NG ini file
> 
>     7. Run Pandora and check the "TK Dodge Standalone" option. Do not check the "TK Dodge RE / Ultimate Combat" option

From reading the steps, this is the proper install for TK Dodge RE on Pandora. It should no longer be an engine issue but a user issue, so closing this thread.

**Closed by Monitor144hz** 2024-05-03 07:49 UTC
Labels: bug
