### ISSUE TITLE
Animated Eating Redux SE and some anims from Immersive Interactions not seen in game

### ISSUE THREAD

**Issue by Zekund** [Monitor144hz/Pandora-Behaviour-Engine-Plus#150] opened 2024-03-19 07:22 UTC
### Version

1.2.2 alpha

### Provide Instructions on Reproducing the Problem

- Animated eating/drinking animations from "Animated Eating Redux SE edition" were not playing. I only tested eating/drinking while standing.

- Some animations from "Immersive Interactions - Animated Actions" such as opening doors, picking up item on table were not working (animation for picking up item on ground works). I haven't tested others.

- Engine log was giving me warning about "True Directional Movement - 360 Horse Archery" patch. I used True Directional Movement so I always ticked 3 TDM patches in Nemesis. I did the same for Pandora.

- I also noticed that OAR gave error and closed skyrim startup due to going over animation limits. So I had to increased it to 65534. I was using the same MO2 profile (same mods) with FNIS+Nemesis and OAR was working with only 32767 anim limit. Somehow numbers of anims seemed to increased for OAR after I turned off FNIS/Nemesis and their outputs and turned on Pandora and its output.

I just stared trying Pandora yesterday. I hope my feedback contributes a bit. Thank you for developing Pandora!

### Provide Relevant Files

[Pandora Output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14646895/Pandora.Output.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment] 2024-03-19 09:55
I'm sure that the issue of some animations from Immersive Animations not working and Animated Eating Redux SE animations not working are a duplicate of #76. The third point is just a warning from dirty edits that can be ignored. 

The fourth point seems unintended, I'm looking into whether it's a bug with OAR or Pandora.

**Comment by Zekund** [comment] 2024-03-19 14:26
I think I uploaded the wrong Pandora output which was after removing Animated Eating mod and 1 more DAR mod. I still have the previous Pandora output with above issues before removal of any mods. So this should be the right output:
[Pandora Output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14651901/Pandora.Output.zip)

**Comment by Monitor144hz** [comment] 2024-05-03 12:47
duplicate #76 so closing this and moving the last point to a new issue

**Closed by Monitor144hz** 2024-05-03 12:47 UTC
Labels: bug
