### ISSUE TITLE
Crash after pressing Launch №2

### ISSUE THREAD

**Issue by Kazyachka** [Monitor144hz/Pandora-Behaviour-Engine-Plus#37] opened 2023-12-22 09:06 UTC
The same problem that was previously explained [here](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/issues/8). Yes, it appeared again, I just want to warn you that it does not work for the Russian language, but I don’t know, maybe there are problems in other languages! And most likely this is due to the same problem as in 0.4.2 "problems with non-English systems and regional settings using the international number system" I’ll say more that everything worked fine from the previous version, but now this error has popped up again, or better yet, a bug

**Comment by Kazyachka** [comment] 2023-12-22 09:08
Yes, it appeared again, I just want to warn you that it does not work for the Russian language, but I don’t know, maybe there are problems in other languages!

**Comment by Monitor144hz** [comment] 2023-12-22 10:23
Fixed in v0.8.1, preloading didn't have the same culture safeguard that patching did. Thanks for reporting, please check if the problem is not fixed in the new version

**Closed by Monitor144hz** 2023-12-22 10:23 UTC
