### ISSUE TITLE
Issue with casting or blocking while moving, reversed weapons with XPMSE

### ISSUE THREAD

**Issue by Kmetran** [Monitor144hz/Pandora-Behaviour-Engine-Plus#68] opened 2024-01-06 23:40 UTC
General information:

Game version: 1.6.659.0.8 (GOG)
Pandora version: [Pandora Behaviour Engine v1.0.0-alpha](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/releases/tag/v1.0.0-alpha)
Skeleton: [XPMSSE Light](https://github.com/acepleiades/XP32-Maximum-Skeleton-Special-Extended/releases/tag/1.1), or XPMSSE 5.05 from Nexus.
Mod Manager: [Mod Organizer 2](https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.5.1rc2)

What my issue is:

The default casting and blocking animations don't work while moving, other animations seem to work fine.

What I have tried so far:

I tried using the Pandora.XPMSE.Patch.v0.6.9-alpha, or the Lite version, as well as not using any.
I tried without True Directional Movement.
I tried without any mod just in case my game has some files randomly corrupted, but the animations work fine in that situation.
I deleted the files created by Pandora, meshes, etc, and re-ran Pandora before each different attempt.

Extra info:

The only thing Engine.log contains outside of `INFO` entries is a `WARN : Dispatcher > "True Directional Movement - 360 Horse Archery" > defaultfemale~horsebehavior > Replace > Text > #0742/errorOutTranslation > FAILED`, but I don't think that's relevant, although I tried without it.

Visual Examples:

Here's how it looks like for me with XPMSSE Basic/Full, hand is down, not animating, the spell just shoots out from the lowered hand:
![how_it_looks_like](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/150628499/9588d710-526c-45cd-a989-4e812b82d98c)

Here's how it looks like for me with XPMSSE Minimal, hand is pointing ahead as he shoots the spell, and the body twists for the animation:
![how_it_should_look_like](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/150628499/819f5213-073e-40d2-aef3-350417e31d3d)

**Comment by Monitor144hz** [comment] 2024-01-07 14:22
Engine.log still contains other entries such as active mods, so it's still recommended you submit this

**Comment by Kmetran** [comment] 2024-01-07 16:03
Alright, let me describe it in more detail then.

Here's my minimal load order for the sake of testing this:

```
Official ESM/DLC
Address Library
PapyrusUtil
SkyUI
XPMSSE Light
Skyrim Unbound Reborn
Pandora Behaviour Engine
Pandora's created data
```

Result:

No worky, with, or without adding the Pandora XPMSE Patch.

Here's my working load order:

```
Official ESM/DLC
Address Library
PapyrusUtil
SkyUI
Skyrim Unbound Reborn
```

Here's my entire Engine.log using the minimal load order, half of it with it the XPMSE Patch enabled:

`INFO : Pandora Mod 1 : Pandora Base (REQUIRED) - v.1.0.0`

There is an extra line if I add the XPMSE Patch, here it is, the second half of the log when I enable the XPMSE Patch:

`INFO : Pandora Mod 2 : XPMSE Full For Pandora - v.1.0.0`

That's all my Engine.log contains at maximum, a whole two lines.

**Comment by Monitor144hz** [comment] 2024-01-07 16:21
Zip up your pandora output and send it to me @Kmetran

**Comment by Kmetran** [comment] 2024-01-07 19:40
Sure thing, here's the outputs.

With XPMSSE Light:

[Pandora_XPMSSE_Light.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13854687/Pandora_XPMSSE_Light.zip)

With XPMSSE v5.05 + Pandora.XPMSE.Patch.v0.6.9-alpha:

[Pandora_XPMSSE_v5.05.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13854688/Pandora_XPMSSE_v5.05.zip)

**Comment by Monitor144hz** [comment] 2024-01-07 19:52
It works with all versions of XPMSE on Nexus, but for some reason it does not work with the github version. I'm guessing some bones were removed in the mesh or something of the sort but the skeleton.hkx was not properly updated to reflect the change. This isn't something I have the time to look into when a viable solution exists so you'll just have to use the Nexus version, which has a compatible minimal version in the fomod installer.

**Comment by Kmetran** [comment] 2024-01-07 19:55
But I HAVE tried using the Nexus version, the output I gave with XPMSSE v5.05 WAS the Nexus version + your patch.

**Comment by Monitor144hz** [comment] 2024-01-07 20:13
After more testing, it's confirmed that it works with the "Full" and "Minimal" version, but not the "Basic" version from Nexus. I'll be working on a fix for this.

**Comment by Kmetran** [comment] 2024-01-07 20:26
I'm sorry if I'm annoying, but I have no idea what I'm doing wrong now in that case.

I just tried installing XPMSSE 5.05 with these options in the installer:

`Extended > XPMS(S)E Latest > RaceMenu + XPMS(S)E MCM > None (default) until the end > Install`

Then I added and enabled Pandora.XPMSE.Patch.v0.6.9-alpha, I deleted the Pandora output, then I run Pandora, close the Pandora window, enter the game, try using spells and see arms not moving.

Am I messing up? Is Extended not Full?

**Comment by Kmetran** [comment] 2024-01-07 20:33
Seems that if I pick Minimal in XPMSSE 5.05, and use the Pandora.XPMSE.Lite.Patch.v0.6.9-alpha, that does work, but only that works for me.

**Comment by Kyationa** [comment] 2024-01-08 19:26
> I'm sorry if I'm annoying, but I have no idea what I'm doing wrong now in that case.
> 
> I just tried installing XPMSSE 5.05 (from Nexus) with these options in the installer:
> 
> `Extended > XPMS(S)E Latest > RaceMenu + XPMS(S)E MCM > Next (with nothing selected, the default) until the end > Install`
> 
> Then I added and enabled `Pandora.XPMSE.Patch.v0.6.9-alpha`, I deleted the Pandora output, then I run Pandora to generate stuff, open the game, try using spells and see arms not moving.
> 
> Am I messing up? Is `Extended` not `Full`?
> 
> It seems that if I pick `Minimal` in XPMSSE 5.05's installer, and use `Pandora.XPMSE.Lite.Patch.v0.6.9-alpha`, it works and the hands move properly when casting, but only `Minimal` works for me.

how is it placed in your load order for XPMSSE and the Pandoara XPMSE patch and what body do you use and where is that placed in load order?

**Comment by Rolothe5th** [comment] 2024-01-08 20:05
wait I min I got basic working on my end...

**Comment by Kmetran** [comment] 2024-01-08 21:13
> how is it placed in your load order for XPMSSE and the Pandoara XPMSE patch and what body do you use and where is that placed in load order?

It's at the end of the load order, I posted my basic load order above, that's all I'm using to reproduce this.

```
DLC
Address Library
PapyrusUtil
Racemenu
SkyUI
Skyrim Unbound Reborn
XPMSSE
Pandora Engine
Pandora XPMSE Patch
Pandora's output
```

I'm was using the vanilla body for the sake of testing this, but since you asked, I just tested with BHUNP and SAM Light (I added them before/above XPMSSE in the list), but it makes no difference.


> wait I min I got basic working on my end...

How'd you do that @Rolothe5th? I just tried using Basic, with both patches, or with none, and it didn't work. Only thing working for me is still Minimal with the Lite patch.

**Comment by Rolothe5th** [comment] 2024-01-10 04:47
> > how is it placed in your load order for XPMSSE and the Pandoara XPMSE patch and what body do you use and where is that placed in load order?
> 
> Here's all I'm using to reproduce this, in the same order as I have it in MO2:
> 
> ```
> DLC
> Address Library
> PapyrusUtil
> Racemenu
> SkyUI
> Skyrim Unbound Reborn
> XPMSSE
> Pandora Engine
> Pandora XPMSE Patch
> Pandora's output
> ```
> 
> I was using the default vanilla body for the sake of testing this, but since you asked, I just tested with BHUNP and SAM Light. (I added them before/above XPMSSE in the list)
> 
> But it makes no difference, as the hands are still down when you cast while moving in third person, instead of actually animating and pointing towards the target like they are while standing still.
> 
> > wait I min I got basic working on my end...
> 
> How'd you do that @Rolothe5th? I just tried using Basic, with both patches, or with none, and it didn't work.
> 
> The only way I got the hands to properly animate in third person when casting or blocking while moving, was with XPMSE Minimal and the Lite patch.

wait wait is it he bug in which projectiles initially fire correctly and then after secs it disappear?

**Comment by Kmetran** [comment] 2024-01-10 13:09
> wait wait is it he bug in which projectiles initially fire correctly and then after secs it disappear?

No, here's a step by step guide to check it for yourself:

1) Equip a spell (like, the default fire spell)
2) Go 3rd person mode
3) Hold w to move forward
4) While holding w, use the spell you equipped earlier
5) Observe the results, is the hand using the spell pointing forward? Then congrats, you don't have the bug. Is the hand not pointing forward, and instead down? You have the bug.

I uploaded two pictures to my first comment so you can see what I mean as well.

**Comment by Rolothe5th** [comment] 2024-01-10 19:11
> > wait wait is it he bug in which projectiles initially fire correctly and then after secs it disappear?
> 
> No, here's a step by step guide to check it for yourself:
> 
> 1. Equip a spell (like, the default fire spell)
> 2. Go 3rd person mode
> 3. Hold w to move forward
> 4. While holding w, use the spell you equipped earlier
> 5. Observe the results, is the hand using the spell pointing forward? Then congrats, you don't have the bug. Is the hand not pointing forward, and instead down? You have the bug.
> 
> I uploaded two pictures to my first comment so you can see what I mean as well.

ye don't have that bug when basic

**Comment by LoAndEvolve** [comment] 2024-01-13 18:19
I have this issue as well. For me the bug occurs when moving the camera while casting concentration spells, not just when moving the character.

**Comment by Dignut** [comment] 2024-01-14 07:28
I'm also encountering this, nothing I do fixes it. extended,basic,minimal, the patch made here, nothing. I'm so confused why it isn't working, its apparently caused by the skeleton arm fix from fnis and nemesis not being applied?

**Comment by SchaiRand** [comment] 2024-01-23 12:18
I've had this bug with v1.0.0 as well. My guess is that the XPMSE Skeleton Arm Fix is not doing anything or it doesn't exist with Pandora. Nemesis by default already have this fix and have no such issue.

**Comment by Astrogrinder** [comment] 2024-01-24 03:39
Came here to say that I have this issue too. Will be waiting for an update, I guess

**Comment by Monitor144hz** [comment] 2024-01-24 19:55
[Pandora XPMSE AIO Patch v1.0.0-alpha-dev.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14043008/Pandora.XPMSE.AIO.Patch.v1.0.0-alpha-dev.zip)

This patch should resolve the issue, it works for both full/minimal versions. Disable all previous versions of the XPMSE patch. 

Once it is confirmed to work on user machines, will add it to the next release as part of the base engine.

**Comment by Kmetran** [comment] 2024-01-24 23:14
I just tried it, it does work for me both with the full version of XPMSE, and the skeleton I was using before.

**Comment by Astrogrinder** [comment] 2024-01-25 09:57
Seem to work for me too on all the versions. Thank you

**Comment by LucaciuSAlex** [comment] 2024-02-03 19:00
Tested today with Pandora XPMSE AIO Patch v1.0.0-alpha-dev.zip after having this issue and it works only with minimal XPMSE. Extended and Basic do not work for me.

**Comment by Monitor144hz** [comment] 2024-02-03 20:53
@LucaciuSAlex use the version v1.1.3 patch

**Comment by Monitor144hz** [comment] 2024-02-03 20:57
can't reproduce, it works flawlessly with all 3 versions for me. attributing to user error

**Closed by Monitor144hz** 2024-02-03 20:57 UTC
Labels: bug, mod

**Comment by jj-code-00** [comment] 2024-08-26 02:00
I'm just going to say this particular bug still occurs when using Racial Body Morphs Redux SSE AE, which uses a different skeleton based on XPMSE. I could not get it fixed and had to switch back to nemesis, in which the bug does not occur.

**Comment by watterson668-cloud** [comment] 2026-04-26 17:22
@Monitor221hz @LucaciuSAlex  pls whereis the 1.1.3 patch ??????
