### ISSUE TITLE
[Bug]: TK Dodge Standalone patch from Maxsu's TK Dodge RE doesn't appear to work with Nemesis

### ISSUE THREAD

**Issue by BetaFalcon13** [Monitor144hz/Pandora-Behaviour-Engine-Plus#182] opened 2024-04-07 20:23 UTC
### Version

v1.3.0-Alpha

### Provide Instructions on Reproducing the Problem

On game version 1.6.1170, download and install TK Dodge NG according to the directions on the mod page (including requirements from other versions of TK Dodge)

Using the Nemesis patches that you will end up installing along with TK Dodge RE - Script Free (a requirement for TK Dodge NG), if you run Pandora and enable the "TK Dodge Standalone" patch when running the engine, it will run just fine, however, when you get in game and try to dodge, you will actually end up performing the dodge animation, but you will be unable to move, and will instead perform the animation stuck in place

I haven't tested this on a clean install, but I have tested on an installation of the game that is otherwise working as expected, and I have tried switching between Nemesis and Pandora without making any other changes. It works as intended using Nemesis, but the player is unable to move during a dodge using Pandora

### Provide Relevant Files

[Pandora_Output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14898855/Pandora_Output.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment] 2024-04-07 21:45
duplicate of #28 

Use this patch: https://www.nexusmods.com/skyrimspecialedition/mods/111788

**Closed by Monitor144hz** 2024-04-07 21:45 UTC
Labels: bug
