### ISSUE TITLE
Contraptions with FNIS mods do not work

### ISSUE THREAD

**Issue by Kyationa** [Monitor144hz/Pandora-Behaviour-Engine-Plus#64] opened 2024-01-03 01:57 UTC
when every I try any contraptions being from "Devious Devices" and others like "Milk Mod Economy" they do not work keeps character in the same one spot the fails when it attempts to put character in the contraption also "ZaZ animation pack 8" has some which don't work also. there is "(DM3) RZAA furniture pack" "SLUTS resume" and "SLUTS cart" and "Simple slavery plus plus" use them but I don't know if there part of the mod its self. "KARTS" and "Pet Project" and there is "Skyrim chain beasts" and "Pamatronic's Deadly Furniture's" and "Prison overhaul patched AE" and this one "Traps NTR(Need Trappy Reality)" here is my Output.
[Pandora Output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13815121/Pandora.Output.zip)

**Comment by Kyationa** [comment] 2024-01-03 03:56
it seems all of these are related to ZaZ animation Pack 8 as all use some resource from ZaZ

**Comment by DarklyNightly** [comment] 2024-01-03 04:23
dupe of #56

**Comment by Kyationa** [comment] 2024-01-03 04:38
only difference is the traps NTR(need trappy reality) dont know what has that having a issue

**Comment by Rolothe5th** [comment] 2024-01-05 20:52
> only difference is the traps NTR(need trappy reality) dont know what has that having a issue

hold up I got traps working fine on my end so its must be issue on your end

**Comment by Kyationa** [comment] 2024-01-05 20:56
> > only difference is the traps NTR(need trappy reality) dont know what has that having a issue
> 
> hold up I got traps working fine on my end so its must be issue on your end

Hmm I'll try a different save when I get a chance and see if it works might be my save.

**Comment by kirby86k** [comment] 2024-01-19 14:11
> > > only difference is the traps NTR(need trappy reality) dont know what has that having a issue
> > 
> > 
> > hold up I got traps working fine on my end so its must be issue on your end
> 
> Hmm I'll try a different save when I get a chance and see if it works might be my save.

It was a common issue when using Nemesis and FNIS together as well, I suppose cuffs and restraints don't work. Unfortunately that's on ZAP and not Pandora.

**Closed** 2024-02-01 22:55 UTC
