### ISSUE TITLE
[Bug]: Animated Potions - Animations don't play, anim object is only attached to hand

### ISSUE THREAD

**Issue by FiftyTifty** [Monitor144hz/Pandora-Behaviour-Engine-Plus#183] opened 2024-04-07 20:29 UTC
### Version

v1.3.0alpha

### Provide Instructions on Reproducing the Problem

Install this mod via MO2: https://www.nexusmods.com/skyrimspecialedition/mods/73819?tab=files
Run Pandora, mod will not be detected.
Start the game. Once the MCM menus are loaded, drink a potion.
No drinking animation will play.
---
This works on the latest Nemesis, which detects the Animated Potions mod when the exact same steps are followed.

Here is the output in the Pandora GUI:
``Resources loaded successfully.

Pandora Mod 1 : Ice skating fixed for real - v.1.0.0
Pandora Mod 2 : True Directional Movement - Procedural Leaning - v.1.0.0
Pandora Mod 3 : True Directional Movement - Headtracking - v.1.0.0
Pandora Mod 4 : Pandora Base - v.1.0.0
Pandora Mod 5 : Some Creature Behavior Bug Fixes - v.1.0.0
Pandora Mod 6 : XPMSE Patch For Pandora - v.1.0.0

FNIS Mod 1 : FNIS_AnimatedPotions_Behavior.hkx

2 animations added to defaultfemale.
2 animations added to defaultmale.

4 total animations added.

Launch finished in 0.61 seconds``

### Provide Relevant Files

Below are the logs from Nemesis and Pandora. I have all my other current mods activated, lmk if you would like them all deactivated for whatever reason.

[Pandora Output.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14898877/Pandora.Output.zip)

[Nemesis_Engine.zip](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/14898878/Nemesis_Engine.zip)

### Contributing To Development

- [X] I read this project's [Contributing To Development](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/wiki/Contributing-To-Development)

**Comment by Monitor144hz** [comment] 2024-05-03 12:42
duplicate of #76

**Closed by Monitor144hz** 2024-05-03 12:42 UTC
Labels: bug
