### ISSUE TITLE
access violation crash when drawing weapons

### ISSUE THREAD

**Issue by hedyl2** [Monitor144hz/Pandora-Behaviour-Engine-Plus#54] opened 2024-01-02 05:10 UTC
Wish I could be a bit more specific here, but it appears to not be behaving well with certain actions. I'm using Precision, Ice Skating Fix, Unblockable, and Standalone Underwater swimming. No other behavior mods. Crash on weapon draw, only when magic is equipped. Slot doesn't matter. Tested this setup with Nemesis and the crash did not persist. Crash log is courtesy of trainwreck

[2024-01-01-21-36-22.log](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/files/13807284/2024-01-01-21-36-22.log)

**Comment by Monitor144hz** [comment] 2024-01-02 09:50
Duplicate of #27, check for solution

**Closed** 2024-01-02 09:50 UTC
