### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by Kamidju13** [Monitor144hz/Pandora-Behaviour-Engine-Plus#211] opened 2024-05-14 13:32 UTC
### Expected behavior

ZaZ Animations And Milk Mod Economy milking mashine Animations is nt working Char Just stand near Furniture!

**Comment by Monitor144hz** [comment] 2024-05-14 21:37
duplicate of #76

**Closed by Monitor144hz** 2024-05-14 21:37 UTC
Labels: enhancement
