### ISSUE TITLE
Crash after pressing Launch

### ISSUE THREAD

**Issue by Kazyachka** [Monitor144hz/Pandora-Behaviour-Engine-Plus#8] opened 2023-11-10 19:43 UTC
I turned off Nemesis, got a crash after pressing the Launch button. I tried disabling some mods (I realized that it was not a matter of mods) and installed NET DETECTOR as needed. As a result, the same crash. And it’s strange that at first it thinks as if it wants to make a patch, but then it crashes

**Comment by Kazyachka** [comment] 2023-11-10 19:54
In general, I didn’t even understand the essence of the problem, since SL (Sex Lab) does not interfere with it, the animations also disappear, the combat also disappears, since I turned off these mods one by one and looked at what led to the failure. And I don’t even know which mod to suspect (but as I said earlier, I don’t think it’s because of the mod)

**Comment by elbadcode** [comment] 2023-11-10 20:10
Its probably not SL stuff causing a crash as those don't have nemesis patches and simply don't get processed and don't play in game. There may be issues I havent seen but so far any time pandora crashes for me it happens bc of a mod conflict that would've resulted in a crash when running nemesis. I've never seen a crash after hitting launch though, usually it happens as soon as I start the program. Make sure to check the log for any info, make sure the output folder is empty and nnot set to read only and try running everything as admin. You can also run the program outside of a mod organizer with just the default patcher and see if it still crashes bc then its probably a dotnet issue not a mods issue. I'm not the author but if you cant figure it out you should probably post your log so he has something to go off of

**Comment by Monitor144hz** [comment] 2023-11-10 20:27
post the Engine.log and state the prerelease version you're using please

**Comment by Kazyachka** [comment] 2023-11-11 10:17
> Its probably not SL stuff causing a crash as those don't have nemesis patches and simply don't get processed and don't play in game. There may be issues I havent seen but so far any time pandora crashes for me it happens bc of a mod conflict that would've resulted in a crash when running nemesis. I've never seen a crash after hitting launch though, usually it happens as soon as I start the program. Make sure to check the log for any info, make sure the output folder is empty and nnot set to read only and try running everything as admin. You can also run the program outside of a mod organizer with just the default patcher and see if it still crashes bc then its probably a dotnet issue not a mods issue. I'm not the author but if you cant figure it out you should probably post your log so he has something to go off of

In your opinion, what could conflict with Pandora? I went through all the options, I don’t have mods for animals and everything related to FNIS (I don’t think that it will cause such errors) I don’t even have any idea what it could be, OAR? I think not either... although a log would help me a lot. If so I knew where to get it.

**Comment by Kazyachka** [comment] 2023-11-11 10:19
> post the Engine.log and state the prerelease version you're using please, as well as a list of all the active behavior patches

Oh, who's that guy here :) Hi, I'm a fan of your mods, you have great projects. Thank you. The only question is where to get this log? after this crash no logs are created

**Comment by Monitor144hz** [comment] 2023-11-11 12:00
@Kazyachka if there is no Engine.log file in the output, please state the version of Pandora you are using and the list of behavior mods you had active when you ran.

**Comment by Kazyachka** [comment] 2023-11-11 16:34
@Monitor144hz (I immediately apologize for the possible incorrect spelling, since I am doing this through Google Translator) This is where the strangeness begins, after launching the Output there is an empty folder. But besides Pandora, all my apps are inactive (turned off in MO2). I haven’t used such nonsense as Fnis. And these errors are also not related to SL, since it almost always crashes after pressing the start button. Version of Pandora Behavior Engine+ V0.3.0 alpha. But.. the strangest thing I noticed was the absence of the Nemesis base mod. I think either because of this or... or I don't know. At least it’s very difficult for me now with the installation, but I would like to leave the old Nemesis as soon as possible

**Comment by Kazyachka** [comment] 2023-11-11 16:44
And hey, have you thought about creating your own discord channel? It would be faster to learn about new mod updates. Speaking of Pandora, I think that it’s not even worth disabling the mods, because after I click start, 5-10 seconds pass and everything seems to be fine, but then a micro-crash happens and a crash occurs. And I think that this has nothing to do with the mods that I have installed. If it was a matter of mods, Pandora would start registering mods, and after that if it crashed, it would leave a log with mods that it doesn’t like... but as I said, something went wrong

**Comment by Kazyachka** [comment] 2023-11-11 16:48
By the way, I completely forgot to mention that I didn’t use anything other than Nemesis. And turned it off in MO2 after installing Pandora. Now I’ll try to completely remove Nenesis (but I think that this is not a solution to the problem, and it will remain so)

**Comment by Kazyachka** [comment] 2023-11-11 16:56
![IMG_1591](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/150479122/4e6d638e-a1bb-4811-a9a4-82387e38b153)
I talked about this

**Comment by Monitor144hz** [comment] 2023-11-11 18:00
> Version of Pandora Behavior Engine+ V0.3.0 alpha.

@Kazyachka 
Use [Pandora Behavior Engine+ V0.4.0 alpha](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/releases/tag/v0.4.0-alpha), issue should be fixed in that version. Likely to be same cause as #5, as I have received similar reports.

Please use the latest version from now on. Let me know if that fixes the problem.

**Comment by Kazyachka** [comment] 2023-11-11 19:02
> > Version of Pandora Behavior Engine+ V0.3.0 alpha.
> 
> @Kazyachka Use [Pandora Behavior Engine+ V0.4.0 alpha](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/releases/tag/v0.4.0-alpha), issue should be fixed in that version. Likely to be same cause as #5, as I have received similar reports.
> 
> Please use the latest version from now on. Let me know if that fixes the problem.

@Monitor144hz 

Oddly enough, I get the same crash on the new version. Are there any installation requirements? (without what mods will it not launch and work?) but I think that’s not even the problem. I was wondering what the problem could be. By the way, this is true, I have Windows 11. And I don’t think that it is not compatible. Strange

**Comment by Kazyachka** [comment] 2023-11-11 19:08
And in general, I think that even the old Pandora was better and more stable than Nemesis (since Nemesis was abandoned halfway through, and they stopped developing it) And the new version of Pandora, which was redesigned from scratch, I think is 3-4 times better than the same Nemesis and even in alpha the choice will be obvious that Pandora is better than the buggy Nemesis (I’ve been putting together a build for myself for years) And I suffered and lost a lot of time precisely because of Nemesis and its clumsiness and crashes.

**Comment by Kazyachka** [comment] 2023-11-11 19:21
> > Version of Pandora Behavior Engine+ V0.3.0 alpha.
> 
> @Kazyachka Use [Pandora Behavior Engine+ V0.4.0 alpha](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/releases/tag/v0.4.0-alpha), issue should be fixed in that version. Likely to be same cause as #5, as I have received similar reports.
> 
> Please use the latest version from now on. Let me know if that fixes the problem.

I don't think it's because of this. Since the person didn’t catch the flight after pressing launch (even if he did catch it, he created a log that he sent to make it easier for the author to identify errors) and here even after launching without MO2 there is an error and a crash. Moreover, the crash occurs without a log... maybe this is something related to the requirements? maybe I'm missing something?

**Comment by Kazyachka** [comment] 2023-11-11 19:32
Crap! I accidentally closed the topic. I'm squirming

**Comment by Monitor144hz** [comment] 2023-11-11 19:51
> I don't think it's because of this. Since the person didn’t catch the flight after pressing launch (even if he did catch it, he created a log that he sent to make it easier for the author to identify errors) and here even after launching without MO2 there is an error and a crash

The person was using a development build that specifically had a block to force the engine to ignore any errors at the cost of worse performance. Please just use it and see before assuming it is not the issue.

**Comment by Kazyachka** [comment] 2023-11-11 20:19
@Monitor144hz 

Maybe again the whole essence of what I wrote was spoiled by the translator. I meant that after installing 0.4.0 the same problem remained. That is, it didn’t go anywhere, the same crash after launch

**Comment by Kazyachka** [comment] 2023-11-11 20:51
@Monitor144hz @elbadcode 

I tried to do as I said @elbadcode but the effect remained the same. That is, I ran it as administrator and made the folders readable. This option can be discarded. I installed NET Returne x32 in addition to NET Returne x64 (I used the latest version 7.1.2) maybe I need to install another version? Although I also think it’s nonsense

**Comment by Monitor144hz** [comment] 2023-11-11 21:01
At this point I suggest disabling mods until you can find the culprit.

**Comment by Kazyachka** [comment] 2023-11-11 21:04
> At this point I suggest disabling mods until you can find the culprit.

@Monitor144hz 

Is everyone such a guilty mod? I don’t think so because it crashes for me even if I install it without mods

**Comment by Monitor144hz** [comment] 2023-11-11 22:03
1. Net Runtime 7+. 
2. Must be 7 or greater.
3. There is nothing beyond installing the mod and running it from MO2
4. No need to enable Nemesis while Pandora active.

I cannot give any further instructions than this unfortunately. I am out of ideas. It must be something to do with your system because I cannot reproduce it reliably on my computer.

**Comment by Kazyachka** [comment] 2023-11-11 22:16
> 1. Net Runtime 7+.
> 2. Must be 7 or greater.
> 3. There is nothing beyond installing the mod and running it from MO2
> 4. No need to enable Nemesis while Pandora active.
> 
> I cannot give any further instructions than this unfortunately. I am out of ideas. It must be something to do with your system because I cannot reproduce it reliably on my computer.

@Monitor144hz 

Hmm... this is getting interesting. There are a lot of NET versions and you can get confused in them: NET Desktop Reuntime, Net Core Reuntime and then SDK. What version of Windows do you have? I think I can draw conclusions from this and maybe we’ll move towards a solution.

**Comment by Kazyachka** [comment] 2023-11-11 22:32
@Monitor144hz 

In general, to put it simply, Pandora Human And Creature Behavior Engine V0.5.0-Beta worked and ran for me on Windows 11. No crashes were noticed, only errors in animations and mods. But I'm not going to install it because it's outdated

**Comment by Monitor144hz** [comment] 2023-11-11 23:03
I am testing on .NET Desktop Runtime 7 with Windows 10, yes. I don't think it's a system problem, perhaps something left over in the game files is interfering. I would appreciate a test on a fresh setup (as in vanilla game with no mods active apart from Pandora and Pandora Base patch) to make sure. I will close this for now because it cannot be proved for certain that the issue is with the program, but feel free to re-open if you find out it is.

**Closed by Monitor144hz** 2023-11-11 23:03 UTC

**Comment by elbadcode** [comment] 2023-11-11 23:08
I'm on windows 11 22h2 with no issues. If you're crashing before a log is generated it definitely could be your OS or dunges.Try updating Windows if you haven't in a while. As for .NET you can run `dotnet --info` and `where.exe dotnet` in terminal to verify install locations. Uninstall x86 sdk if present. Runtimes are fine to have as many as you want, but only have the one x64 SDK install. Ensure that your  x64 runtime is correctly listed in your Path environment variable and there is no x86 version in path.

Otherwise if you clean install windows and install visual studio 2022 with all major feature sets you should have all of that setup automatically. This may be the best way to avoid having so many installs

**Comment by Kazyachka** [comment] 2023-11-11 23:11
@Monitor144hz No problem! I'll try to test it tomorrow and try to find the problem or at least a solution. I think that I will not open this topic again since there is really no evidence. When you created the old Pandora you had Windows 10 and the old version started for me and worked normally without any crashes. But I will try to find the problem and at least solve it. Tomorrow I'll try to test it on a build without mods. If it starts, of course (if not), then you will need to look for the problem. But in any case, I will often write here with changes (if any)

**Comment by Kazyachka** [comment] 2023-11-12 12:18
@elbadcode 

Yes, most likely you are right, the failures are related to the OS or NET, but these two methods did not help, I completely restored Windows by resetting it to zero. After which I installed a clean NET SDK. And nothing has changed, the same crash that occurs 5-10 seconds after pressing Launch (but the process itself does not start, it just crashes)

**Comment by elbadcode** [comment] 2023-11-12 12:34
You clicked on Reset this PC in the basic windows settings menu? You should install the newest version rather than just resetting. Resetting will not help if your OS is simply outdated. You shouldn't need to clean install this time since you already reset. Windows 11 23H2 is latest available if you choose to get it. I updated to 23H1 which is where it stops if you let it autoupdate. Brings some new features to file explorer. That's really all I can say at this point. If that still fails with only the default pandora patch then your only good option is to build it yourself which should be easy if you can decipher the error warnings in visual studio even if you can't code. Good luck, there's really nothing more anyone can say for help so please go try everything thoroughly 👍

**Comment by Kazyachka** [comment] 2023-11-12 12:45
@elbadcode 

Alas, I am not a developer and I have no control over any types of languages. Yes, but I installed the latest 23H2 update and nothing happened to install the NET SDK. that is, it crashed and continues to crash after pressing Launch (but the most important strange thing is that it crashes before installation)

**Comment by Kazyachka** [comment] 2023-11-12 14:52
@Monitor144hz, @elbadcode 

I was very curious if this had something to do with the version of Skyrim? After all, there are a lot of differences from 1.5.97 to the latest version. Very strange. If, for example, Pandora was conceived for the latest version of Skyrim (although not a fact)

**Comment by Kazyachka** [comment] 2023-11-12 18:35
![Без имени](https://github.com/Monitor144hz/Pandora-Behaviour-Engine-Plus/assets/150479122/df424f9e-a605-4596-99dd-4e27e8b2771f)
hm....

**Comment by Monitor144hz** [comment] 2023-11-13 08:11
@Kazyachka Version of Skyrim doesn't matter, behavior is version independant. I don't know why you have that message, did you install the correct desktop runtime?

**Comment by elbadcode** [comment] 2023-11-13 14:16
Possible issue related to windows versioning. If so my apologies for saying to get latest version. For now I recommend you stop at 22h2 as I can confirm that version is perfectly functional. Might not be due to the windows version but I'm having a somewhat similar issue now. 

As I said in my previous comment I just updated to 23h1. one modlist on 1.5.97 works, Pandora works although I did experience a crash after hitting patch for the first time, but I did get Pandora to patch eventually after deleting the output folder and some mods and double-checked write perms. After that I couldn't get into the game on my 1.6.64 modlist due to a few SKSE plugins crashing. Though it's odd that only a few crashed while others were fine, it's very possible that 23H1/23H2 simply have incompatibilities with their C# and C++ runtimes or some default settings that are causing issues. I'm going to investigate for myself and check all my env variables and reinstall runtimes but I'd say stick to 22H2 for safety.

**Comment by Kazyachka** [comment] 2023-11-13 22:16
> Possible issue related to windows versioning. If so my apologies for saying to get latest version. For now I recommend you stop at 22h2 as I can confirm that version is perfectly functional. Might not be due to the windows version but I'm having a somewhat similar issue now.
> 
> As I said in my previous comment I just updated to 23h1. one modlist on 1.5.97 works, Pandora works although I did experience a crash after hitting patch for the first time, but I did get Pandora to patch eventually after deleting the output folder and some mods and double-checked write perms. After that I couldn't get into the game on my 1.6.64 modlist due to a few SKSE plugins crashing. Though it's odd that only a few crashed while others were fine, it's very possible that 23H1/23H2 simply have incompatibilities with their C# and C++ runtimes or some default settings that are causing issues. I'm going to investigate for myself and check all my env variables and reinstall runtimes but I'd say stick to 22H2 for safety.

@elbadcode 

Yes, thank you, very interesting theory. But I give you 100% that this is not related to the versions of Windows, since the 22H2 had this crash (the crash occurs after pressing Launch, after 5-10 seconds) and that the 23H2 has the same problem. Also, this is not related to mods since it crashes even without mods. I dug through many options for solving this problem, but it was all down the drain (not one option was correct)

**Comment by Monitor144hz** [comment] 2023-11-14 15:47
@Kazyachka try version 0.4.2, perhaps the root cause was a system language issue (duplicate of #10 )

**Comment by Kazyachka** [comment] 2023-11-15 09:26
@Monitor144hz @elbadcode 

Please tag it as a bug. Since this was a bug that was fixed in the new version. It had to do with language. My native language is Russian (and the system language is logically also Russian) And this caused crashes without a log. Now everything is working well.

**Comment by Kazyachka** [comment] 2023-11-15 09:30
> @Kazyachka try version 0.4.2, perhaps the root cause was a system language issue (duplicate of #10 )

@Monitor144hz 

Thank you, yes this helped. Thanks to you, I cleaned the system and installed new wood on the system. I didn’t dare do it for a year, but I did it. Thank you

**Comment by Monitor144hz** [comment] 2023-11-15 10:23
Thanks for confirming it has the same cause as #10. Thank you for troubleshooting all throughout as well.

**Comment by Kazyachka** [comment] 2023-11-15 10:27
> Thanks for confirming it has the same cause as #10. Thank you for troubleshooting all throughout as well.

@Monitor144hz 

Thank you very much, thanks to you I did what I didn’t dare to do for a year. I cleaned the system completely. Reinstalled the drivers and tweaks. Completely optimized the system ❤️🙂

**Comment by Kazyachka** [comment] 2023-12-22 09:05
The same problem happened again
